#!/bin/bash
#
# ~/.xinitrc
#

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

get_session(){
          local dbus_args=(--sh-syntax --exit-with-session)
    dbus_args+=(awesome)
          echo "dbus-launch ${dbus_args[*]}"
}

exec $(get_session)
